#define NOP      0x0
#define PUSH     0x1
#define POP      0x2
#define STORE    0x3
#define LOAD     0x4
#define ADD      0x5
#define SUB      0x6
#define MUL      0x7
#define DIV      0x8
#define JMP      0x9
#define JZ       0x10
#define JNZ      0x11
#define PRINT    0xef
#define END_EXEC 0xff
